Repository back-seung/jpa-playground, pull requests merged in 2024-01, with the labels that each got.

#3 2024.01.18 - 4장 정리 이승상
  chpater-04/4-04.md
  chpater-04/4-05.md
  chpater-04/4-07.md
Labels: size/L

#4 2024.01.23 5장, 6장 정리 이승상
  chpater-05/5-03 양방향 연관관계.md
  chpater-05/5-04 연관관계 주인.md
  chpater-06/6-02 일대다.md
Labels: size/M

#5 2024.01.23 - 5,6장 정리 황승현
  chpater-05/5-0 단어 정리.md
  chpater-05/5-1 단방향 연관관계.md
  chpater-05/5-2 연관관계 사용.md
  chpater-06/6-1 다대일.md
Labels: size/XL

#7 6장 정리.
  chpater-06/6.4 다대다.md
  chpater-06/img.png
  playground/build.gradle.kts
  playground/src/main/kotlin/com/play/jpaplayground/ch06_ManyToMany/ManyToManyService.kt
  playground/src/main/kotlin/com/play/jpaplayground/ch06_ManyToMany/Member.kt
  playground/src/main/kotlin/com/play/jpaplayground/ch06_ManyToMany/Product.kt
Labels: size/L

#8 2024.01.24 7-3.4/5/6 이승상
  chpater-07/7-3.4 비식별 관계로 구현.md
  chpater-07/7-3.5 일대일 식별 관계.md
  chpater-07/7-3.6 식별, 비식별 관계의 장단점.md
Labels: size/L

#9 2024.01.25 - 7장 정리 황승현
  chpater-07/7-1 상속 관계 매핑.md
  chpater-07/7-2 @MappedSuperclass.md
Labels: size/L

#10 2024.1.25 7-3.[1,2,3] 정리
  chpater-07/7-3.1 식별관계 vs 비식별관계.md
  chpater-07/7-3.2 비식별 관계 매핑.md
  chpater-07/7-3.3 식별 관계 매핑.md
Labels: size/L

#12 2024.01.30 - 8장 정리 황승현
  chpater-08/8-4 영속성 전이(CASCADE).md
  chpater-08/8-5 고아 객체.md
  chpater-08/8-6 영속성 전이 + 고아객체, 생명주기.md
Labels: size/M
